# Generated by Django 4.2.4 on 2023-08-31 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_artisan_departmenthead_mentor_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_done',
            field=models.BooleanField(default=False),
        ),
    ]
