# Generated by Django 4.2.4 on 2023-08-31 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_profile_profile_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='username',
        ),
    ]
