# Generated by Django 4.2.4 on 2023-08-31 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_user_profile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='validateprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='validateprofile',
            name='last_name',
        ),
    ]
