# Generated by Django 4.2.4 on 2023-09-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_rename_username_profile_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otpcode',
            options={'verbose_name': 'کد فعال سازی', 'verbose_name_plural': 'کد های فعال سازی'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'پروفایل', 'verbose_name_plural': 'پروفایل ها'},
        ),
        migrations.AlterModelOptions(
            name='validateprofile',
            options={'verbose_name': 'تایید پروفایل', 'verbose_name_plural': 'تایید پروفایل ها'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='degree',
            field=models.CharField(choices=[('PHD', 'Phd'), ('POSTGRADUATED', 'postgraduated'), ('UNDERGRADUATED', 'undergraduated'), ('ASSOCIATE_OF_ART', 'associate_of_art'), ('ASSOCIATE_OF_SCIENCE', 'associate_of_science')], default='ASSOCIATE_OF_SCIENCE'),
        ),
    ]
