# Generated by Django 4.2.4 on 2023-09-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_profile_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='degree',
            field=models.CharField(choices=[('PHD', 'Phd'), ('PG', 'postgraduated'), ('UG', 'undergraduated'), ('AOF', 'associate_of_art'), ('AOS', 'associate_of_science')], default='AOS'),
        ),
    ]
