# Generated by Django 4.2.4 on 2023-09-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_profile_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='degree',
            field=models.CharField(choices=[('PHD', 'Phd')], default='AOS'),
        ),
    ]
