# Generated by Django 4.2.4 on 2023-09-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_profile_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='degree',
            field=models.CharField(choices=[('PHD', 'Phd'), ('Postgraduated', 'postgraduated'), ('undergraduated', 'undergraduated'), ('Associate of art', 'associate of art'), ('associate of science', 'associate of science')], default='associate of science'),
        ),
    ]
