# Generated by Django 4.2.4 on 2023-09-02 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_profile_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='degree',
            field=models.CharField(choices=[('PHD', 'دکتری'), ('Postgraduated', 'کارشناسی ارشد'), ('Undergraduated', 'کارشناسی'), ('Associate_of_art', 'دیپلم کاردانی'), ('Associate_of_science', 'دیپلم تجربی'), ('Associate_of_math', 'دیپلم ریاضی'), ('Associate_of_liberal_arts', 'دیپلم انسانی')], default='Associate_of_science'),
        ),
    ]
