# Generated by Django 4.2.5 on 2023-09-20 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_validateprofile_is_validate_delete_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Artisan',
        ),
        migrations.DeleteModel(
            name='DepartmentHead',
        ),
        migrations.DeleteModel(
            name='Mentor',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
