version: '3'
services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: jcob
      POSTGRES_PASSWORD: PassWord
      POSTGRES_DB: rasor