# Generated by Django 4.2.5 on 2023-09-13 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
    ]
