# Generated by Django 4.2.5 on 2023-09-13 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
    ]
