# Generated by Django 4.2.5 on 2023-09-14 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_remove_order_total_price_order_price_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
