# Generated by Django 4.2.5 on 2023-09-22 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_remove_enrollment_course_remove_enrollment_student_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='title',
        ),
    ]
