# Generated by Django 4.2.5 on 2023-09-24 07:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '__first__'),
        ('product', '0015_rename_name_product_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='course',
            field=models.ForeignKey(default=1000, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dashboard.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.PositiveBigIntegerField(validators=[django.core.validators.MaxValueValidator(1001001000)]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.PositiveBigIntegerField(validators=[django.core.validators.MaxValueValidator(1001001000)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveBigIntegerField(validators=[django.core.validators.MaxValueValidator(1001001000)]),
        ),
    ]
