# Generated by Django 4.2.5 on 2023-09-24 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '__first__'),
        ('product', '0016_orderitem_course_alter_order_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dashboard.course'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='product.product'),
        ),
    ]
