# Generated by Django 4.2.5 on 2023-09-08 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-created_at'], 'verbose_name': 'نظر', 'verbose_name_plural': 'نظرات'},
        ),
    ]
