# Generated by Django 4.2.5 on 2023-10-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[('academics', 'اکادمیک'), ('expriences', 'تجارب')], default='exprience', max_length=20),
        ),
    ]
