# Generated by Django 4.2.5 on 2023-09-15 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_coursecontent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Mentor',
            new_name='mentor',
        ),
    ]
