# Generated by Django 4.2.5 on 2023-09-20 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0008_courseregistered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseregistered',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_registered', to=settings.AUTH_USER_MODEL),
        ),
    ]
