# Generated by Django 4.2.4 on 2023-08-28 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_product_thumbnail_alter_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-updated_at'], 'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
    ]
