# Generated by Django 4.2.4 on 2023-09-05 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_product_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
