# Generated by Django 4.2.4 on 2023-08-31 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_listbox_options_alter_news_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=155, null=True)),
                ('provience', models.CharField(blank=True, max_length=155, null=True)),
                ('city', models.CharField(blank=True, max_length=155, null=True)),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PageContent1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'متن صفحه بخش اول',
                'verbose_name_plural': 'متن صفحه بخش اول',
            },
        ),
        migrations.CreateModel(
            name='PageContent2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'متن صفحه بخش دوم',
                'verbose_name_plural': 'متن صفحه بخش دوم',
            },
        ),
        migrations.CreateModel(
            name='ShareLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.CharField(max_length=255)),
                ('telegram', models.CharField(max_length=255)),
                ('gmail', models.CharField(max_length=255)),
                ('youtube', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='news',
            name='author',
        ),
    ]
