# Generated by Django 4.2.5 on 2023-09-07 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_contactus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
    ]
