# Generated by Django 4.2.5 on 2023-09-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_delete_contactus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharelinks',
            old_name='gmail',
            new_name='link',
        ),
        migrations.RemoveField(
            model_name='sharelinks',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='sharelinks',
            name='telegram',
        ),
        migrations.RemoveField(
            model_name='sharelinks',
            name='youtube',
        ),
        migrations.AddField(
            model_name='sharelinks',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
