# Generated by Django 4.2.5 on 2023-09-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_rename_gmail_sharelinks_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharelinks',
            name='title',
            field=models.CharField(choices=[('TELEGRAM', 'Telegram'), ('INSTAGRAM', 'Instagram'), ('TWITTER', 'Twitter'), ('GOOGLE', 'Google'), ('PINTREST', 'Pintrest'), ('LINKEDIN', 'Linkedin'), ('YOUTUBE', 'Youtube'), ('FACEBOOK', 'Facebook')], default='TELEGRAM'),
        ),
    ]
