# Generated by Django 4.2.5 on 2023-09-11 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_aboutus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'درباره ما', 'verbose_name_plural': 'درباره ما'},
        ),
    ]
